from flask_wtf import Form
from wtforms import StringField,BooleanField,IntegerField,DecimalField
from wtforms.validators import DataRequired

class SymptomsForm(Form):
	age=IntegerField('age',default=20)
	bp=IntegerField('bp',default=0)
	sg=DecimalField('sg',default=0,places=1,rounding=None)
	al=IntegerField('al', default=0)
	sugar=IntegerField('sugar',default=0)
	rbc=BooleanField('rbc', default=False)
	blood_glucose=IntegerField('blood_glucose',default=0)
	blood_urea=IntegerField('blood_urea',default=0)
	serum=IntegerField('serum',default=0)
	sodium=IntegerField('sodium',default=0)
	potassium=IntegerField('potassium',default=0)
	hemoglobin=IntegerField('hemoglobin',default=0)
	pcv=IntegerField('pcv',default=0)
	wbc=IntegerField('wbc',default=0)
	rc=IntegerField('rc',default=0)
	pus_cell=BooleanField('pus_cell',default=False)
	pcc=BooleanField('pcc',default=False)
	bacteria=BooleanField('bacteria',default=False)
	ht=BooleanField('ht',default=False)
	diabetes=BooleanField('diabetes',default=False)
	cad=BooleanField('cad',default=False)
	appetite=BooleanField('appetite',default=False)
	pedal=BooleanField('pedal',default=False)
	anemia=BooleanField('anemia',default=False)
	ckd=StringField('ckd',default=0)
